### ISSUE TITLE
Failed to instantiate [ch.qos.logback.classic.LoggerContext]

### ISSUE THREAD

**Issue by 09094080-Tao-Jiao** [heshengjun811/rocketmq-demo#1]
Help:

Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
java.lang.ExceptionInInitializerError
	at org.apache.rocketmq.client.producer.DefaultMQProducer.<init>(DefaultMQProducer.java:64)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.<init>(DefaultMQProducer.java:146)
	at org.apache.rocketmq.logappender.common.ProducerInstance.getInstance(ProducerInstance.java:66)
	at org.apache.rocketmq.logappender.logback.RocketmqLogbackAppender.start(RocketmqLogbackAppender.java:98)
	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:148)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
	at org.apache.rocketmq.logging.Slf4jLoggerFactory.<init>(Slf4jLoggerFactory.java:26)
	at org.apache.rocketmq.logging.InternalLoggerFactory.<clinit>(InternalLoggerFactory.java:65)
	at org.apache.rocketmq.remoting.common.RemotingUtil.<clinit>(RemotingUtil.java:40)
	at org.apache.rocketmq.client.ClientConfig.<init>(ClientConfig.java:38)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.<init>(DefaultMQProducer.java:203)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.<init>(DefaultMQProducer.java:146)
	at org.apache.rocketmq.example.quickstart.Producer.main(Producer.java:34)
Caused by: java.lang.RuntimeException: [RocketMQ] Logger init failed, please check logger
	at org.apache.rocketmq.logging.InternalLoggerFactory.getLoggerFactory(InternalLoggerFactory.java:54)
	at org.apache.rocketmq.logging.InternalLoggerFactory.getLogger(InternalLoggerFactory.java:39)
	at org.apache.rocketmq.client.log.ClientLogger.createLogger(ClientLogger.java:86)
	at org.apache.rocketmq.client.log.ClientLogger.<clinit>(ClientLogger.java:53)
	... 27 more

**Comment by heshengjun811** [comment]
嗯, 这个是有问题的, 我是给RocketMQ 社区题问题用的这个, 我也不知道是啥原因, 你可以把logback.xml文件去掉,应该就可以正常运行

**Comment by 09094080-Tao-Jiao** [comment]
好的，谢谢！
